-- begin CONTRACTSYSTEM_CONTRACT
alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references CONTRACTSYSTEM_CONTRACTOR(ID)^
create index IDX_CONTRACTSYSTEM_CONTRACT_CONTRACTOR on CONTRACTSYSTEM_CONTRACT (CONTRACTOR_ID)^
-- end CONTRACTSYSTEM_CONTRACT
-- begin CONTRACTSYSTEM_CONTRACTOR
create unique index IDX_CONTRACTSYSTEM_CONTRACTOR_UNIQ_EMAIL on CONTRACTSYSTEM_CONTRACTOR (EMAIL) ^
-- end CONTRACTSYSTEM_CONTRACTOR

-- begin CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK
alter table CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CCFDL_CONTRACT foreign key (CONTRACT_ID) references CONTRACTSYSTEM_CONTRACT(ID)^
alter table CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CCFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK
