-- begin CONTRACTSYSTEM_CONTRACT
alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references CONTRACTSYSTEM_CONTRACTOR(ID)^
alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID)^
create index IDX_CONTRACTSYSTEM_CONTRACT_DOCUMENT on CONTRACTSYSTEM_CONTRACT (DOCUMENT_ID)^
-- end CONTRACTSYSTEM_CONTRACT
-- begin CONTRACTSYSTEM_CONTRACTOR
create unique index IDX_CONTRACTSYSTEM_CONTRACTOR_UNIQ_EMAIL on CONTRACTSYSTEM_CONTRACTOR (EMAIL) ^
-- end CONTRACTSYSTEM_CONTRACTOR
