alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
create index IDX_CONTRACTSYSTEM_CONTRACT_DOCUMENT on CONTRACTSYSTEM_CONTRACT (DOCUMENT_ID);
