alter table CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CCFDL_CONTRACT foreign key (CONTRACT_ID) references CONTRACTSYSTEM_CONTRACT(ID);
alter table CONTRACTSYSTEM_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CCFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
