create table CONTRACTSYSTEM_ENTITY_WITH_MANY_TO_MANY_FILE_DESCRIPTOR_FILE_DESCRIPTOR_LINK (
    ENTITY_WITH_MANY_TO_MANY_FILE_DESCRIPTOR_ID varchar(36) not null,
    FILE_DESCRIPTOR_ID varchar(36) not null,
    primary key (ENTITY_WITH_MANY_TO_MANY_FILE_DESCRIPTOR_ID, FILE_DESCRIPTOR_ID)
);
