alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID);
alter table CONTRACTSYSTEM_CONTRACT add constraint FK_CONTRACTSYSTEM_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references CONTRACTSYSTEM_CONTRACTOR(ID);
create index IDX_CONTRACTSYSTEM_CONTRACT_DOCUMENT on CONTRACTSYSTEM_CONTRACT (DOCUMENT_ID);
create index IDX_CONTRACTSYSTEM_CONTRACT_CONTRACTOR on CONTRACTSYSTEM_CONTRACT (CONTRACTOR_ID);
