-- update CONTRACTSYSTEM_CONTRACT_FD_WITH_DEFAULT_BEHAVIOUR set CONTRACTOR_ID = <default_value> where CONTRACTOR_ID is null ;
alter table CONTRACTSYSTEM_CONTRACT_FD_WITH_DEFAULT_BEHAVIOUR alter column CONTRACTOR_ID set not null ;
