-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column NUMBER_ varchar(255) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING set NUMBER_ = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING alter column NUMBER_ set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column NUMBER_ varchar(255) ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column CONTRACTOR_ID varchar(36) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING set CONTRACTOR_ID = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING alter column CONTRACTOR_ID set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column CONTRACTOR_ID varchar(36) not null ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column DOCUMENT_ID varchar(36) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING set DOCUMENT_ID = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING alter column DOCUMENT_ID set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING add column DOCUMENT_ID varchar(36) not null ;
