-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING set NUMBER_ = <default_value> where NUMBER_ is null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_ENABLED_VERSIONING alter column NUMBER_ set not null ;
