-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column NUMBER_ varchar(255) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR set NUMBER_ = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR alter column NUMBER_ set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column NUMBER_ varchar(255) ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column CONTRACTOR_ID varchar(36) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR set CONTRACTOR_ID = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR alter column CONTRACTOR_ID set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column CONTRACTOR_ID varchar(36) not null ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column DOCUMENT_ID varchar(36) ^
-- update CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR set DOCUMENT_ID = <default_value> ;
-- alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR alter column DOCUMENT_ID set not null ;
alter table CONTRACTSYSTEM_CONTRACT_WD_WITH_DEFAULT_BEHAVIOUR add column DOCUMENT_ID varchar(36) not null ;
