-- begin WEBDAV_DEMO_CONTRACT
alter table WEBDAV_DEMO_CONTRACT add constraint FK_WEBDAV_DEMO_CONTRACT_DOCUMENT foreign key (DOCUMENT_ID) references SYS_FILE(ID)^
alter table WEBDAV_DEMO_CONTRACT add constraint FK_WEBDAV_DEMO_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references WEBDAV_DEMO_CONTRACTOR(ID)^
create index IDX_WEBDAV_DEMO_CONTRACT_DOCUMENT on WEBDAV_DEMO_CONTRACT (DOCUMENT_ID)^
create index IDX_WEBDAV_DEMO_CONTRACT_CONTRACTOR on WEBDAV_DEMO_CONTRACT (CONTRACTOR_ID)^
-- end WEBDAV_DEMO_CONTRACT
-- begin WEBDAV_DEMO_CONTRACTOR
create unique index IDX_WEBDAV_DEMO_CONTRACTOR_UK_EMAIL on WEBDAV_DEMO_CONTRACTOR (EMAIL) where DELETE_TS is null ^
-- end WEBDAV_DEMO_CONTRACTOR
-- begin WEBDAV_DEMO_WEBDAV_CONTRACT
alter table WEBDAV_DEMO_WEBDAV_CONTRACT add constraint FK_WEBDAV_DEMO_WEBDAV_CONTRACT_CONTRACTOR foreign key (CONTRACTOR_ID) references WEBDAV_DEMO_CONTRACTOR(ID)^
alter table WEBDAV_DEMO_WEBDAV_CONTRACT add constraint FK_WEBDAV_DEMO_WEBDAV_CONTRACT_DOCUMENT foreign key (DOCUMENT_ID) references WEBDAV_WEBDAV_DOCUMENT(ID)^
-- end WEBDAV_DEMO_WEBDAV_CONTRACT
-- begin WEBDAV_DEMO_CONTRACT_WITH_DISABLED_WEBDAV
alter table WEBDAV_DEMO_CONTRACT_WITH_DISABLED_WEBDAV add constraint FK_WEBDAV_DEMO_CONTRACT_WITH_DISABLED_WEBDAV_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
-- end WEBDAV_DEMO_CONTRACT_WITH_DISABLED_WEBDAV
-- begin WEBDAV_DEMO_CONTRACT_WITH_SIMPLE_FILE_DESCRIPTOR
alter table WEBDAV_DEMO_CONTRACT_WITH_SIMPLE_FILE_DESCRIPTOR add constraint FK_WEBDAV_DEMO_CONTRACT_WITH_SIMPLE_FILE_DESCRIPTOR_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
-- end WEBDAV_DEMO_CONTRACT_WITH_SIMPLE_FILE_DESCRIPTOR

-- begin WEBDAV_DEMO_MANY
alter table WEBDAV_DEMO_MANY add constraint FK_MAN_ENTITY_MANY_FD foreign key (ENTITY_MANY_ID) references WEBDAV_DEMO_ENTITY_MANY_FD(ID)^
alter table WEBDAV_DEMO_MANY add constraint FK_MAN_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end WEBDAV_DEMO_MANY
