package com.haulmont.contractsystem.web.contractfdwithenabledwebdavenabledversioning;

import com.haulmont.cuba.gui.components.AbstractEditor;
import com.haulmont.contractsystem.entity.ContractFDWithEnabledWebdavEnabledVersioning;

public class ContractFDWithEnabledWebdavEnabledVersioningEdit extends AbstractEditor<ContractFDWithEnabledWebdavEnabledVersioning> {
}